M48
; DRILL file {KiCad (6.0.0)} date Mon Nov 14 00:42:42 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-14T00:42:42-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1693
%
G90
G05
T1
X3.0Y-1.5748
X3.6142Y-1.5748
T2
X3.3071Y-1.5748
T3
X0.6299Y-0.1969
X0.6299Y-2.0866
X3.0709Y-0.2165
X3.0709Y-2.0866
T0
M30
